### ISSUE TITLE
File Transfer Proxy listed as chat room

### ISSUE THREAD

**Issue by lyn1337** [conversejs/converse.js#1023]
The address for MUCs inVerse defaults to shows incorrect subdomains / other server components. 
XEP-0045 suggests using "conference.shakespeare.lit".

**Comment by turbocloud** [comment]
I have the same issue with conversejs (3.3.2). When logged in click on rooms > show rooms > all components are shown as link. Even going further clicking component for MUC I can start a chat room with a nickname. Server has NO rooms created nor installed.
![conversejs1](https://user-images.githubusercontent.com/6852588/36826121-fbdfc1f4-1cd0-11e8-807e-1fe2e887035e.jpg)

![conversejs2](https://user-images.githubusercontent.com/6852588/36826127-04be863e-1cd1-11e8-8559-a4f2090ebff3.jpg)


![converse1](https://user-images.githubusercontent.com/6852588/36826115-f59dd204-1cd0-11e8-826b-5a944290c128.jpg)

**Comment by jcbrand** [comment]
@turbocloud can you give me an account on your XMPP server (or tell me where I can register)? Then I'll debug.

**Comment by turbocloud** [comment]
@jcbrand it is still in development but here you go:
Registration: https://jabber.yorktondigital.ca/test.htm
Testing: https://jabber.yorktondigital.ca/

**Comment by jcbrand** [comment]
@turbocloud I looked at your server's MUC component. The 2nd item listed is a MUC room, so that's correct. The 1st item listed is the File Transfer service, which shouldn't be shown as a room.

However, when making that query, there's no reliable information to show whether the item is a room or something else. The MUC XEP makes the assumption that all items returned are rooms, which is also the assumption that converse.js makes.

The relevant section of the XEP is here: https://xmpp.org/extensions/xep-0045.html#disco-rooms

The only thing I can currently think of is to change the UI to require the user to first click the `info` icon to get more info before and then based on that extra info it's clear whether the item is a room or not and through that make it possible to open the room. That's something I'm not going to do for the 3.3.x branch. I'm already working on a new bootstrap based UI for the 4.x branch and a change such as this might go in there (unless some other solution comes up).

**Comment by jcbrand** [comment]
@lyn1337 is your issue the same as @turbocloud's, or something else? If it's something else, please provide me with an account or details of your XMPP server.

**Comment by lyn1337** [comment]
@jcbrand "Show rooms" works as intended, listing them correctly.
The issue Im having is a gateway component shown as the preset muc service. I think this might also be related to what you have pointed out, but there is no way to change the ordering.

Wouldnt it be easier to compose the preset with "conference..." for now?

**Comment by jcbrand** [comment]
> Wouldnt it be easier to compose the preset with "conference..." for now?

We can't just make assumptions like that. Many MUC components don't start with `conference.` but for example with `muc.` or with `chat.`.

Can you give me an account on your server?

**Comment by lyn1337** [comment]
Now converse doesn't even hit the right one.
Most servers I came across use conference, server configs and the xep mentioned suggests it as well.

One may still adjust it...

**Comment by jcbrand** [comment]
Actually, the XEP uses `chat.shakespeare.lit`.

**Comment by jcbrand** [comment]
I found and fixed a bug this morning that caused clients advertising MUC being shown in the `server` field. I think this addresses @lyn1337's issue.

I've therefore renamed this ticket to make it applicable to what @turbocloud mentioned (ideally this would have been two separate tickets).

**Comment by lyn1337** [comment]
@jcbrand
is this change live (demo) yet?

**Comment by turbocloud** [comment]
Hi jcbrand,

great work to the quick fix.
Will there be a new version to download in the next days/weeks ?
Would like to install before going online.

**Comment by jcbrand** [comment]
The changes will only be live once the next release has been made which will be in the next two weeks or so.

**Comment by Echolon** [comment]
@jcbrand I think this can be closed

**Comment by jcbrand** [comment]
Thanks @Echolon
