### ISSUE TITLE
Support for fullscreen view mode + mobile combined?

### ISSUE THREAD

**Issue by ge0rg** [conversejs/converse.js#1057]
Hi,

I want to run inverse by default on the desktop page and have the mobile theme on mobile devices. However, with the new `view_mode` setting I have only two settings to choose from:

* "fullscreen" - looks good on Desktop but has no dedicated mobile support
* "mobile" - shows Converse on Desktop (not desired) and mobile (good) on mobile

Can't we make "mobile" implicitly supported in either inverse or converse view mode?

P.S: The 3.3.4 release is missing `mobile.min.css`

**Comment by jcbrand** [comment]
> Can't we make "mobile" implicitly supported in either inverse or converse view mode?

In the master branch I've already [merged the mobile css into converse.css](https://github.com/conversejs/converse.js/commit/bfc308187451a2d1cb3490f7d00bf1dc2a2b73f9).

So already there's no need for a separate CSS file.

I also still want to merge inverse.css into converse.css, so that there's eventually only one css file for all usecases.

Support for mobile however goes further than just CSS, there are also a few subtle JS changes between mobile mode and other modes.

I'm not sure how one could automatically switch between modes from within JavaScript.

I use the following redirection code in Nginx to redirect mobile devices to m.conversejs.org, which hosts the mobile code (essentially the same JavaScript code but with `view_mode` set to `mobile`).

```
    location = / {
        ## start mobile redirection code
        set $mobile_rewrite do_not_perform;
        if ($http_user_agent ~* "(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|m
          set $mobile_rewrite perform;
        }
        if ($http_user_agent ~* "^(1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(d
          set $mobile_rewrite perform;
        }
        if ($mobile_rewrite = perform) {
          rewrite       ^(.*)   https://m.conversejs.org$1      redirect;
          break;
        }
        ## End mobile redirection code

        root    /home/conversejs/converse.js/;
        index   index.html;
    }
```

**Comment by poVoq** [comment]
With the changes in the GUI rendering backend, will this come to version 7.0?

The PineTab is coming soon and I got the first complaint https://github.com/poVoq/conversejs-ubports/issues/7 that my mobile app for Ubuntu Touch (that uses the mobile view-mode) breaks on tablets :)

**Comment by jcbrand** [comment]
No, unfortunately the GUI updates are not related to this.
