### ISSUE TITLE
I.E. sometimes sends header context-length: 0 on first post to http-bind

### ISSUE THREAD

**Issue by henkdemarie** [conversejs/converse.js#1073]
On I.E. logging in with the converse js controlbox often fails.
If so, it keeps failing until I.E. is restarted and temp files deleted (a couple of times).

I noticed that when it fails, the first post to http-bind is sent with context-length: 0 in its request headers.
While te request body still looks like this:
`<body xml:lang='en' content='text/xml; charset=utf-8' rid='123456789' xmlns='http://jabber.org/protocol/httpbind' to='server.com' wait='60' hold='1' ver='1.6' xmpp:version='1.0' xmlns:xmpp='urn:xmpp:xbosh'/>`

request headers are:
- Aanvraag	POST /http-bind/ HTTP/1.1
- Accept	\*/\*
- Content-Type	text/xml; charset=utf-8
- Referer	http://server/chat/
- Accept-Language	nl-NL
- Accept-Encoding	gzip, deflate
- User-Agent	Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko
- Host	server
- Connection	Keep-Alive
- Cache-Control	no-cache
- Content-Length	0

Thanks in advance,

**Comment by jcbrand** [comment]
> On I.E. logging in with the converse js controlbox often fails.

How do users log in, manually, or some other way?

>  it keeps failing until I.E. is restarted and temp files deleted

You can try to call `window.sessionStorage.clear()` from the developer console and see if that fixes things. It would be useful debugging information to have as well.

---

I don't know what the issue is but I have a hypothesis.

Strophe.js sometimes sends out empty "polling" requests if there aren't any open requests held by the BOSH connection manager (your server).

It might be that upon loading converse.js, that such an empty "polling" request is sent out, which is why you have `Content-Type: 0` (I *think*, haven't confirmed).

Looks like this can happen when `Strophe.Connection.prototype.attach` is called, which would get called when `keepalive` is set to `true`.

I think what should then happen is that the server should respond with something like "Invalid SID" and then Converse.js should try to reestablish a new XMPP session.

What response is received from the server in these cases?

**Comment by jcbrand** [comment]
I believe the empty request is sent out here: https://github.com/strophe/strophejs/blob/e81ce285b9be2bacc2bf7c83d1207231427367d9/strophe.js#L5355

You could put a breakpoint in converse.js or an alert/console.log or something, to see if that's the case.

**Comment by henkdemarie** [comment]
> How do users log in, manually, or some other   way?

Manually, with the loginpanel

> You can try to call window.sessionStorage.clear() from the developer console and see if that fixes things. It would be useful debugging information to have as well.

Will try this monday (i have this issue at work)

> Looks like this can happen when Strophe.Connection.prototype.attach is called, which would get called when keepalive is set to true.

I already tried setting keepalive to false, before posting this issue, but without result.

> What response is received from the server in these cases?

Bad request. I think the server says bad request, because the request has a xml payload but has header content-length 0 . Not sure though. Open Fire is on a server managed by another company :/

**Comment by henkdemarie** [comment]
> I believe the empty request is sent out here: https://github.com/strophe/strophejs/blob/e81ce285b9be2bacc2bf7c83d1207231427367d9/strophe.js#L5355

> You could put a breakpoint in converse.js or an alert/console.log or something, to see if that's the case.

This breakpoint isn't "hit", when i log in

**Comment by henkdemarie** [comment]
window.sessionStorage.clear() + ctrl-F5 helps for some time, until i get "bad request" responses again. (usualy after 1-10 succesful requests to http-bind)

It seems we only have this issue at work in the virual environment.
I tried logging in with I.E. on another computer and it works fine :/
