### ISSUE TITLE
Button to scroll to bottom, when scrolled up

### ISSUE THREAD

**Issue by albjeremias** [conversejs/converse.js#1118]
on long logs on chat rooms, would be cool.. instead of scrolling down

**Comment by jcbrand** [comment]
I'm not convinced that such a button is necessary.
You can press "end" on your keyboard and the chat will scroll down to the bottom.

**Comment by licaon-kter** [comment]
Could we reopen this?

> You can press "end" on your keyboard and the chat will scroll down to the bottom.

Except it doesn't... if the input area is focused, right? So then I have to "use mouse to click the messages area" in order to "be able to press end on my keyboard" and by this time the question still stands... Why not a button to scroll to bottom instead of me juggling between mouse movement, mouse clicks and keyboard? Just reuse the "you have unread messages" pop-up.
