### ISSUE TITLE
cookies are lost after firefox restart

### ISSUE THREAD

**Issue by albjeremias** [conversejs/converse.js#1119]
is it possilbe that cookies last longeer? Because on mastodon and other services i just keep my cookies with the addon firefox multicontainer, so its not a security/privacy issue! is there a place in the code to look for cookie expiration? :)

**Comment by jcbrand** [comment]
No cookies aren't lost because cookies aren't used for authentication and no cookies are created.

Matthew Wild has created an experimental Cookie auth plugin for Prosody (see [mod_auth_cookie](https://modules.prosody.im/mod_auth_http_cookie.html)), which uses SASL External with Cookies, but it relies on cookies from an external web service (i.e. the Prosody server doesn't generate any cookies).

Other XMPP servers don't support any Cookie auth.

So, currently the only way to maintain a session across browser restarts is to store the user's XMPP password in localStorage, which I don't think is a good idea.
