### ISSUE TITLE
Participants get duplicated when gaining ownership of a MUC

### ISSUE THREAD

**Issue by Ppjet6** [conversejs/converse.js#1146]
Running 7c20e16ea (master).

## Steps to reproduce

- Join an existing muc
- Get ownership (set affiliation from another account/resource)

## What happens

A message saying the user gained ownership is displayed, and then join messages from every other participants are displayed in the room, and they also get duplicated in the userlist.

## What I expect

Only the message about ownership is displayed.

**Comment by jcbrand** [comment]
@Ppjet6 What would help me a lot to reproduce the bug and fix it would be if you could give me browser logs.

Can you please reproduce the behaviour and then save the browser logs to a file and attach it here or send it to me?

It's important that `debug` is `true` so that the stanzas are included in the logs.

I can then replay logs to see what happened and use them to construct a test.

**Comment by jcbrand** [comment]
@Ppjet6 I think this is fixed now.

I noticed this problem when making someone a `member`, not `owner`, but the bug is the same AFAIK.
