### ISSUE TITLE
 Could not restore session for jid: pessek@xxx.xxx.org

### ISSUE THREAD

**Issue by rheman** [conversejs/converse.js#1147]
I am using the lastest stable release of conversejs. (3.3.4) with ejabberd 18.04
But some  time I have the following error message.

I am using authentication prebind

```
        prebind_url: xxxxxx,
        authentication: 'prebind',
        bosh_service_url: xxxxxxxxxx,

```
```
2018-08-01T06:33:56+03:00 WARNING: Could not restore session for jid: pessek@xxx.xxx.org Error message: _restore: no restoreable session. 
_converse.log @ converse.js:39563
conversejs:39653

```
And I need to restart my ejabberd server. 
Really dont know what's wrong.

Need Help. Best regards

**Comment by jcbrand** [comment]
That message simply means that there is no previous BOSH session that can be restored and that the user will need to log in again (either automaticaly or manually, depending on how Converse is set up).

Converse (actually Strophe.js) tries to restore BOSH sessions by looking for RID and SID tokens in the browser's sessionStorage and then sending them to the XMPP server.

You're getting a message `no restoreable session` from Strophe.js, which means you don't have the relevant tokens in order to restore a session with.

Generally this isn't an issue and Converse will either try to fetch new BOSH tokens (from the 'prebind_url', or render a login form).

I don't see any reason why you have to restart ejabberd. If that's really the case, then check the logs of ejabberd.
