### ISSUE TITLE
Use an in-memory localStorage replacement when the computer is public

### ISSUE THREAD

**Issue by linkmauve** [conversejs/converse.js#1148]
This will remove the requirement of explicitly logging off, and should generally be much better wrt privacy, as it will avoid storing anything which could be recovered later on disk.

**Comment by jcbrand** [comment]
I don't see how this will be workable, because you'll then need to fetch all data again when the tab gets refreshed.

Converse is used in multiple different ways, not only as a single-page-app, but also as a popup chat integrated into websites. In the latter use-case it's critical that data gets cached across pageloads.

**Comment by linkmauve** [comment]
Couldn’t those use `sessionStorage`, which should generally be done in-memory in the browser?

**Comment by jcbrand** [comment]
Also (when logged in on a public computer), it's not a requirement to explicitly log off, if you close the tab, then the data also gets deleted (because it's stored in sessionStorage).

**Comment by jcbrand** [comment]
> Couldn’t those use sessionStorage, which should generally be done in-memory in the browser?

This is the status quo.
