### ISSUE TITLE
Overriding renderMessage

### ISSUE THREAD

**Issue by Ghasan** [conversejs/converse.js#1165]
Hi all,

I want to customize the renderMessage to support custom payload, but I don't want to write the thing, so I am thinking is there away to customize it based on the original. Something like this:

```javascript
{
    overrides: {
        ChatBoxView: {
            renderMessage: function (attr) {
                var elem = this.renderMessage(attr);
                // Do custom changes to elem;
                return elem;
            }
        }
    }
}
```
Is this possible?

Thanks.

**Comment by jcbrand** [comment]
Yes, every method on any Backbone.Model or Backbone.View can be overridden in this way, however you need to make the code part of a plugin and whitelist that plugin.

More info here: https://github.com/conversejs/converse.js/blob/master/docs/source/plugin_development.rst

I'm linking to the Github page because the live docs are still a bit behind, they'll be updated with the 4.0.0 release.

Then another thing... the `renderMessage` method no longer exists. So if you're going to work from the master branch (which you probably should), then you'll have to override the `render` method of the [MessageView](https://github.com/conversejs/converse.js/blob/2db3db9bab04c66c4164e32bdf042281c3d3e87f/src/converse-message-view.js#L99) class.

**Comment by Ghasan** [comment]
@jcbrand  Thank you very much, I found it (y)
