### ISSUE TITLE
Improve the listing of rooms

### ISSUE THREAD

**Issue by linkmauve** [conversejs/converse.js#1174]
This would include, in no particular order:
- [x] Disco#info each room once we have the list, this is mandatory for most of the other steps.
- [x] Sort alphabetically.
- [x] Only display items which are rooms, that is category=conference, type=text.
- [ ] ~Only display rooms with more than zero participants.~
- [ ] ~Display the number of participants.~
- [x] Display the MUC avatar, as per the [MUC Avatars XEP](https://linkmauve.fr/extensions/muc-avatars.html).

**Comment by linkmauve** [comment]
Oh, so ordering per number of participants, instead of alphabetically, like we do at https://chat.jabberfr.org/ for instance?  Why not.

**Comment by jcbrand** [comment]
Related to #1851

**Comment by jcbrand** [comment]
I'm not going to implement the following suggestions:

>  Only display rooms with more than zero participants.

If rooms with zero participants clutter up the list, then leave them and keep them bookmarked.

>  Display the number of participants.

You can open a room and click the avatar to quickly see info about it, and you can also see the number of participants in the sidebar. I believe trying to also show this info in the rooms list will make it too busy and result in information overload.

If someone can provide a clean UI design that shows otherwise, I'll reconsider.
