### ISSUE TITLE
Release 4.0.1 from CDN not working with IE11 and EDGE browser

### ISSUE THREAD

**Issue by MotoGP-Fan** [conversejs/converse.js#1220]
My System:
MS Windows10 Pro - Version 1803 (Build 17134.285)
Microsoft Edge 42.17134.1.0
IE11: 11.285.17134.0 with update 11.0.85

Seams that current release from CDN is not working with the MS browsers.
Screenshot is taken from EDGE. After typing the login data an click on LOGIN nothing more is going on.
And with IE11 you can't see anything on conversejs.org.

![conversejs org_with_edge-browser](https://user-images.githubusercontent.com/30147533/45948228-61985280-bff7-11e8-91cb-3c1fb93ee859.png)

**Comment by jcbrand** [comment]
Support for IE11 has been dropped, since we don't have the resources to keep developing for it.

If someone wanted to take on the task of making Converse work for it, or contracted me to do it, then support might be added again, but for now that's the case.

Concerning Edge, do you see any errors being reported in the browser console?

**Comment by MotoGP-Fan** [comment]
These are the messages during the access to conversejs.org including the attempt to log in:
![conversejs org_edge_console](https://user-images.githubusercontent.com/30147533/45953184-9ca38180-c009-11e8-887d-22596b8a1212.png)
