### ISSUE TITLE
Adding a bookmark should prefill the room name

### ISSUE THREAD

**Issue by deleolajide** [conversejs/converse.js#1222]
Adding a bookmark, the bookmark name should be pre-filled with the room name.

![image](https://user-images.githubusercontent.com/110731/46005068-5bb07900-c0ac-11e8-9821-fcca55d01859.png)

Originally reported [here](https://github.com/igniterealtime/Pade/issues/61)

**Comment by laurenmayers** [comment]
I'd like to work on this - if no one else has started?

**Comment by jcbrand** [comment]
Hi @laurenmayers 

Thank you for offering to fix this issue!

I wanted to quickly look into what needs to be done so that I could give you some pointers, but then I saw that fixing it would take 5 minutes, so I quickly did it.

If you're interested in working on another ticket perhaps, take a look at the issues marked with [good first issue](https://github.com/conversejs/converse.js/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22).

Let me know if you have any questions about a particular issue.

**Comment by laurenmayers** [comment]
Thanks @jcbrand! I'll check out those issues.
