### ISSUE TITLE
Omemo not working on conversejs.org website / no lock icon present / no fingerprints in contact cards.

### ISSUE THREAD

**Issue by goors** [conversejs/converse.js#1245]
Just opened two brand new users on conversejs.org. Loggedin as one and another (one firefox, other chrome), added each other to rooster. I can see Omemo fingerprint for both users in their profile but no Omemo fingerprints are visible in contact cards for the other user. 

So it looks to me guys that your own website does not work with Omemo. I dont know if you tested that or not but i spend last week figuring out why omemo plugin does not work and I was unable to figure that one out.

So please do comment.

**Comment by jcbrand** [comment]
I just checked and it works for me.

Are you using your own XMPP server or did you register users on the conversejs.org server?

Converse is as XMPP client only part of the equation, the XMPP server also plays a role.

From your report it sounds like the device lists don't get shared between the two users. That's why you don't see the fingerprints and why you don't see the lock icon (although you do see your own fingerprint). Perhaps your server doesn't properly support PEP?

**Comment by goors** [comment]
I have used conversejs server. Register user on that conversejs home page (two of them) and trying chrome for one, firefox for other.

I am having save problems on my own ejabbered server. Sometimes omemo is working and most of the time not.

Try to open brand new two accounts and to the same thing as me. I tried with several new users and it i same every time.

**Comment by piotrmoskal** [comment]
@jcbrand @goors I confirm the same incorrect behavior. I tested on Windows 8.1 (latest version of Chrome, Opera, Firefox and MSIEv11) and on Ubuntu 18.04-18.10 (Chrome, Firefox). I can perform specific tests if you @jcbrand want and send results (e.g. video from carrying them out) via email.

**Comment by licaon-kter** [comment]
For ejabberd do you have pubsub on `open` or `whitelist`?

**Comment by goors** [comment]
@licaon-kter i have it on open.
none of omemo javascript implementations work for me (jsxc or converse). i tired like bunch of other jabber servers including converse it does not work.... it only works on Gajim.

**Comment by jfreakazoid** [comment]
Hello everyone. Is there any updated about this? I'm facing the same issue and I could determine that my prosody server is properly setup becauce when I use the converse webpage I'm able to use OMEMO but if I use my hosted one I'm not.

**Comment by danjde** [comment]
Hi Friends!
I've just installed (from git) Converse.js "v4.2.0" on my VPS Debian Stretch, Prosody 0.11, 
Converse.js is hooked to my right BOSH path.
The issue is the same. On any other (non web) client OMEMO is running, from [another Convers.js](https://inverse.chat/)  it's visible but from [my own Converse.js](https://www.3x1t.org/converse/fullscreen.html) the padlock is not visible.

I'm obviously mistaken for some parameter ..


Many thanks!

Davide

**Comment by jcbrand** [comment]
@danjde Have you seen this? https://conversejs.org/docs/html/dependencies.html?highlight=omemo#libsignal

**Comment by danjde** [comment]
Hi @jcbrand and thanks for your help, very useful!
But I don't have much experience with javascript, Could you suggest me how install libsignal and its dependencies?
I've run into converse.js directory:

`npm install libsignal`

But I don't see the file "libsignal-protocol.js".
And I'm not sure if this procedure is correct.
Could you give (to every users) some useful tips? :-)

Many thanks!

Davide

**Comment by licaon-kter** [comment]
@danjde Got the files from `dist`: 
https://github.com/signalapp/libsignal-protocol-javascript

And in **index.html** fix the path

**Comment by danjde** [comment]
Perfect @licaon-kter !
"gitted" libsignal-protocol-javascript into "3rdparty" new directory and the edited fullscreen.html as below:

`<script src="3rdparty/libsignal-protocol-javascript/dist/libsignal-protocol.js"></script>`

and voilà, OMEMO now is running!

Many many thanks to all!

Davide

**Comment by danjde** [comment]
..hoops!
I spoke too soon.
The padlock is now visible but if I try to send it in OMEMO mode the box containing the message to be sent remains gray and the message does not start. 
No errors server side.
Eventually how I could debug Converse.js?

Many thanks again :-)
