### ISSUE TITLE
Some of dependencies are removed from headless package.json, but still required

### ISSUE THREAD

**Issue by cmrd-senya** [conversejs/converse.js#1352]
At https://github.com/conversejs/converse.js/commit/3f7ffd025a98ffb5deb4709c2f4bb25139d3ddbc#diff-8d8848d744f09155a6ed06111726618c some of dependencies have been removed, but they are still required.

For instance `jed` is not in the `package.json` anymore, but it is required in https://github.com/conversejs/converse.js/blob/master/src/headless/i18n.js which is required in https://github.com/conversejs/converse.js/blob/master/src/headless/converse-core.js. Therefore the only way to use `@converse/headless` is to manually add dependencies like `jed` to your local dependencies.

We should either remove the depending code from `@converse/headless` or add the dependencies to `package.json` back again.

**Comment by jcbrand** [comment]
@cmrd-senya What do you think? [jed](https://github.com/messageformat/Jed) is used for translations. I'm not sure whether something like that should go into the headless build or not.

**Comment by cmrd-senya** [comment]
Module `i18n` depends on `jed` and currently is a part of the headless build. The only thing why `i18n` is referenced in the `converse-core` module is localization initialization. I think that we can extract this code out from the `converse-core` and move it somewhere else.

**Comment by kevinfaguiar** [comment]
Just to leave recorded here: while playing with @converse/headless (https://www.npmjs.com/package/@converse/headless) I tried a simple example like this:
```javascript
import "@converse/headless/converse-chatboxes";   // Backbone Collection and Models for chat boxes
import "@converse/headless/converse-mam";         // XEP-0313 Message Archive Management
import "@converse/headless/converse-roster";      // Contacts Roster
import "@converse/headless/converse-vcard";       // XEP-0054 VCard-temp

import converse from "@converse/headless/converse-core";
```
When running this code these were the missing packages:
- backbone 
- es6-promise 
- jed 
- moment 
- pluggable.js 
- sizzle 
- backbone.browserStorage 
- backbone.overview 
- backbone.vdomview 
- strophejs-plugin-ping
-  jquery

After installing all these the warnings in build time had gone.

**Comment by jcbrand** [comment]
@kevinfaguiar: backbone, es6-promise, moment, pluggable.js are all set as dependencies in the package.json of @converse/headless.

See here: https://github.com/conversejs/converse.js/blob/master/src/headless/package.json#L25

jQuery is not a dependency of @converse/headless and is not used, so I don't know why you think it's a missing dependency.

Concerning the `snabdom` errors, that's because you need webpack aliases.
See here: https://github.com/conversejs/converse.js/blob/master/webpack.config.js#L91

We should probably document that somewhere, or make a fix so that those aliases are no longer necessary.

**Comment by kevinfaguiar** [comment]
> @kevinfaguiar: backbone, es6-promise, moment, pluggable.js are all set as dependencies in the package.json of @converse/headless.
> 
> See here: https://github.com/conversejs/converse.js/blob/master/src/headless/package.json#L25

The problem here, I think, is that the dependencies are listed under a **"devDependencies"** tag in **package.json**. So, when I install **@converse/headless** as a dependency to my project these devDependencies are not fetched... I think this is the default behaviour of using NPM...

A simple fix would be changing "devDependencies" to "dependencies" here, since **@converse/headless** is not a distrib file: https://github.com/conversejs/converse.js/blob/master/src/headless/package.json#L24 

A complex one would be building the @converse/headless into a single distrib file, which would demand extra work and code rewrite to make the modules (like "@converse/headless/converse-chatboxes") plugabble...

---

> jQuery is not a dependency of @converse/headless and is not used, so I don't know why you think it's a missing dependency.

It seems to me it is this "jquery", probably solved with the alias (I wasn't aware of this alias until now) : https://github.com/conversejs/converse.js/blob/5b4ce87a4d1ae6998ce1bc90e792697309b58a28/webpack.config.js#L96

---

> Concerning the `snabdom` errors, that's because you need webpack aliases.
> See here: https://github.com/conversejs/converse.js/blob/master/webpack.config.js#L91
> 
> We should probably document that somewhere, or make a fix so that those aliases are no longer necessary.

Yeah, I wasn't aware these alias were necessary. Maybe using relative paths to fix the problem?

**Comment by jcbrand** [comment]
Hi @kevinfaguiar,

thanks for your detailed response and for your patience in trying to use the headless build.

You're right, we need to have a distribution build of `converse-headless.js` to be used by 3rd party projects.

I've now made the relevant changes (see [here](https://github.com/conversejs/converse.js/commit/11c1b01692049a7d395c280083a3a2f2a9bd6ecb)) so that there is a file `dist/converse-headless.js` inside `@converse/headless` and the `main` key of the package.json points to it.

I've also created a quick and dirty [headless-example](https://github.com/conversejs/headless-example) which uses `@converse/headless` and which you can look at.

Because these changes are not released yet, you'll need to clone this repo and then `npm link` in `@converse/headless` so that you can have the latest code in your project. The `headless-example` README explains how you can do this.

I'm also closing this issue because I've now added Jed as a dependency, which is what this was about. Feel free to create new issues if you run into any problems.

Good luck and let me know how it goes!
