### ISSUE TITLE
Social Login / OID Connect SSO?

### ISSUE THREAD

**Issue by poVoq** [conversejs/converse.js#1391]
Would be nice if it was possible to allow SSO via OpenID-Connect (OAuth2) so that users can auto register and login easily via an external service?
It seems like there is a plugin for Prosody on the server side:
https://github.com/rwth-acis/prosody-auth-OIDC

I would mainly like to combine it with my own OID-Connect service from Hubzilla, but this should also allow people to easily sign up with google/github etc. And use that to login easily.

**Comment by jcbrand** [comment]
There is an OAuth plugin, but it's currently not part of the core build (I've been holding off because it's quite large due to the hello.js dependency and also because I wanted to still make some updates, like updating the VCard automatically from the OAuth data).

https://github.com/conversejs/converse.js/blob/master/src/converse-oauth.js

I've used it with [mod_auth_oauthbearer](https://modules.prosody.im/mod_auth_oauthbearer.html).

**Comment by poVoq** [comment]
Would it be possible to use passport.js instead? http://www.passportjs.org/
Or is that only for nodejs server side applications?

**Comment by jcbrand** [comment]
I don't know, I'm not interested in using any other library unless it's clear that it's superior and worth the effort.
