### ISSUE TITLE
[Infrastructure] Simple tiny Docker image

### ISSUE THREAD

**Issue by openscript** [conversejs/converse.js#1427]
Dear community

Thank you very much for this great project.

I've created a small Docker image which hosts converse.js. You can check it out here: https://github.com/openscript/conversejs-docker

I've also published the image to Docker Hub: https://hub.docker.com/r/openscript/conversejs

If you have some feedback, don't hesitate to write me.

Robin

**Comment by jcbrand** [comment]
Hi @openscript, thank you for sharing your Docker config with us. I see you've even included Punjab.

I think it makes sense to have an official Docker image for Converse.js and I've been thinking about and working on a Docker config for some time now

The config I've been working on is for using Converse.js with Prosody as backend, but it would be cool if it was configurable so that you could instead use a different XMPP server, or no server at all (like with your config).

If you're interested in working with me on such a config, let me know.
