### ISSUE TITLE
You're not allowed to send messages in this room

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#1533]
Since https://github.com/conversejs/converse.js/commit/f84c201437b67f159198dc1726876cdfdb931fff in `conversations@conference.siacs.eu`

FYI `ejabberd@conference.process-one.net` is ok.

**Comment by jcbrand** [comment]
Indeed, I'm able to replicate this.

According to XEP-0045, a user is given the role of "visitor" in order to remove their ability to chat in the MUC. See here: https://xmpp.org/extensions/xep-0045.html#revokevoice

I think the issue here is that the Conversations MUC is not moderated, so the above rule doesn't apply.

**Comment by weiss** [comment]
Thanks for this fix!

So you don't allow visitors to send a message in moderated room?  Shouldn't this be left to the server?  So the server can implement e.g. the following [suggestion][1]?

> In handling messages sent by visitors in a moderated room, a MUC service MAY queue each message for approval by a moderator and MAY inform the sender that the message is being held for approval

[1]: https://xmpp.org/extensions/xep-0045.html#impl-service

**Comment by jcbrand** [comment]
@weiss I need this feature for a project I'm working on currently. We can make it configurable in order to support that use-case. Are you aware of any projects or servers that do this?

**Comment by weiss** [comment]
> Are you aware of any projects or servers that do this?

No, I'm not, so no reason to touch the behavior I guess.
