### ISSUE TITLE
Clicking chat title should open info modal instead of requiring separate icon

### ISSUE THREAD

**Issue by Nyco** [conversejs/converse.js#1611]
# Context: solve major pain points one by one

We conducted a study:
Major pain points of Converse after a small user test series #1580
https://github.com/conversejs/converse.js/issues/1580

We have already designed a solution to the major pain points (scored 9):
Create/join channel (groupchat) #1593
https://github.com/conversejs/converse.js/issues/1593
Not delivered yet.

Now, in this current ticket, we are addressing these:
* "i"
* Channel menu
* Contact profile

![58100928-e9fae180-7bde-11e9-9db7-a431b7ae3aaf](https://user-images.githubusercontent.com/25348/59784870-c3a29180-92c3-11e9-8bbe-024a17aba9c4.png)

Thanks to feedback, we will address this in another ticket:
* Quit/exit/leave chat

# Vocabulary 

The "chat pane" is the right side of Converse (not left pane, list of conversations).
The "banner" is the infos and buttons at the top of the chat pane.

Please correct the vocabulary, so we have common wording.

# Problems

## Pain points

Users don't understand why there is:
* duplicate infos when they click in the "i" button (channels)
* a card while the avatar+name is not clickable

## Expressed needs

Users want to click on the name, JID and avatar:
* one-to-one: to see the contact's profile
* channels: to see the channels details

# Solution

## Channels chat banner

* make JID and name clickable (left)
  * when clicked, display the content of the current "i" dialog box
* remove the "i" button (right)

For the quit/leave/exit, config and bookmarks, we'll see in another issue.

## One-to-one chat banner

* make avatar, JID and name clickable (left)
  * when clicked, display the content of the current card dialog box
* remove card (right)

For the quit/exit/leave, we'll see in another issue.

## Both cases

Same height for the banner (pixel perfect)

**Comment by jcbrand** [comment]
> remove "quit" (right)

How do you leave a groupchat then?

**Comment by Nyco** [comment]
> How do you leave a groupchat then?
"Why quit?"
That's what most users said during our tests.

Leaving a channel belongs to the IRC and ICQ era.

In modern/contemporary team chats like Slack, Mattermost, RocketChat, Zulip (even in mobile interpersonal chats like WhatsApp, FB Messenger, Telegram), you just enter and stay. It is a very rare use case to leave a channel.

**Comment by jcbrand** [comment]
Uh no... you can definitely leave a chat in Slack. It's available in the dropdown when you click the gear icon. I'm pretty sure the same applies to (almost?) all the other chats you've mentioned.

**Comment by Nyco** [comment]
OK, let's split the quit/leave/exit in another issue.

Meanwhile, I reorg the whole ticket.

**Comment by Nyco** [comment]
https://github.com/conversejs/converse.js/pull/1612

**Comment by jcbrand** [comment]
@Nyco, @chaizeg 

I've been thinking of this change last night and want to write down some thoughts.

Currently I'm considering rejecting the associated PR #1612, not because I don't agree with the premise, but because I think its change is too superficial and that too little thinking has gone into it.

Simply removing the info icon and making the title clickable is in my opinion not much of an improvement and might even create more confusion. Why? Because the wrench and bookmark icons are still on the top right where the info icon used to be and we're thereby creating another inconsistency (e.g. _"why have icons for those, but for the other modal you have to click the title?"_).

We already we have some inconsistency with some things showing up in a modal and others (the config and bookmark forms) showing up inside the chat itself. I'm torn about this one, because some customers prefer stuff rendering inside the chat boxes, it makes especially sense when using the `overlay` view mode. _(BTW this brings up another thing I want to mention. When you come up with UX suggestions, you need to consider not only the `fullscreen` view mode, but also the `overlay` and `embedded` view modes, and any PR needs to take those into consideration as well.)_

Therefore, to do this right, I think if we were to make the title clickable, then we need to somehow combine all those forms and modals into one place, so that the end result is simpler, more consistent and less confusing than what we have now.

However, this isn't an easy or quick change to make. IMO we need more consideration of both UX and technical requirements, to come up with a solution that works on both ends.

**Comment by Nyco** [comment]
> Currently I'm considering rejecting the associated PR #1612, not because I don't agree with the premise, but because I think its change is too superficial and that too little thinking has gone into it.

OK, clear, we're closing this ticket, and we will create another one based on your thoughts and our user tests. The sooner the better to review/rework a contribution :)

Yes, we understand the pain on dichotomy "modal vs in-chat"... :'( We'll put some work into this. I personally would not consider consistency as the main criterion, probably adding KISS (Keep it Simple Stupid) and POLA (Principle of least astonishment) criteria. From what we have tested so far, regular users are not affected by this issue/dichotomy, as it is just transparent to them.

**Comment by jcbrand** [comment]
OK, FWIW IMO we don't have to close this ticket, but it's fine with me if you want to start fresh in a new one.

**Comment by jcbrand** [comment]
> From what we have tested so far, regular users are not affected by this issue/dichotomy, as it is just transparent to them.

Ok, interesting.
