### ISSUE TITLE
converse.js failes on vcard plugin on click invoke on 5.0.3 on http:// needs https://

### ISSUE THREAD

**Issue by mreid0345** [conversejs/converse.js#1716]
I love the software, it solves so many of our issues, but:
having it not run on https out of the box is going to really limit your market
i read your forums, your users wont know how to fix that.

I suggest, and its only a suggestion from an avid user on the build for my agency i work for:

you dont load the vcard plugin on http. That way that functionality for it can be removed for http.

Note:: i am trying it now with whitelisting all plugins in the whitelist possibilities except 'converse-vcard'
that was my workaround, so maybe just a condition on the plugin init

thanks 👍

**Comment by jcbrand** [comment]
Thank you for the suggestion @mreid0345.

I've considered your suggestion, however I don't think it makes sense to accommodate people serving Converse over HTTP because for most use-cases HTTPS should be used and in the few legitimate use-cases where HTTP might be fine, people can create self-signed certificates, use Let's Encrypt or serve over localhost.

If we update converse-vcard to also work over HTTP, then I'm sure some people will start serving Converse publicly over HTTP, so in a way it's good that due to this issue (**subtle.crypto** not being available via HTTP) they're discouraged from doing so.
