### ISSUE TITLE
Chatboxes stay empty after logging out and in again

### ISSUE THREAD

**Issue by ChaosKid42** [conversejs/converse.js#1735]
The MUC chatboxes open but stay empty if you log in immediately after log off.

1. Go to converse.js
2. Trusted device off and log in
3. Open MUC chatbox (messages are shown)
4. Log off
5. Log in (no page reload in between)
6. Open MUC (messages are not shown)

**Expected behavior**
Messages are shown

**Environment (please complete the following information):**
 - Desktop
 - Browser Chrome
 - Converse.js version 5.0.3

Ejabberd 19.08 self-hosted

**Comment by licaon-kter** [comment]
Seeing the same too sometimes, after logoff you need to CTRL-F5 force reload. 

As with other issues reported by me, unless you cleanly logout and force reload (some sort of the cleanest state possible) stuff will randomly be broken :(

**Comment by ChaosKid42** [comment]
For now I'm simply using the following ugly hack:
```diff
diff --git a/src/headless/converse-core.js b/src/headless/converse-core.js
index d27a9c9f8..eaaa3ff0f 100644
--- a/src/headless/converse-core.js
+++ b/src/headless/converse-core.js
@@ -548,6 +548,7 @@ function clearSession  () {
      * @event _converse#clearSession
      */
     _converse.api.trigger('clearSession');
+    location.reload();
 }
```
But maybe this should be solved correctly by someone more educated than me :-)

**Comment by MotoGP-Fan** [comment]
Maybe this helps to locate the issue

Tested with:
Prosody 0.11.2
Firefox 69.0 + Chrome 77.0.3865.75

Converse 5.0.3 on local installation
Converse 5.0.3 over external "cdn" setup
(both with minified js+css)

converse.initialize({
debug: true,
authentication: 'login',
bosh_service_url: 'https://example.de/http-bind',
locked_domain: 'example.de',
allow_registration: false,
show_send_button: true,
roster_groups: true,
archived_messages_page_size: 25,
message_carbons: true,
theme: 'default',
view_mode: 'fullscreen'
});

**Problem:**
As soon as you add a MUC to your bookmarks and quit Conversejs, this message appears - see pic
If you login again immediately after logout no chat messages will be displayed.
To display received messages you need to press Ctrl+F5 when you are logged in.
It is also possible to press Ctrl+F5 after log out.

**If you delete all bookmarked MUCs, everything seems to work as usual (no "error message appears after logout).**

If you need more information pls. let me know.
Pls. test Conversejs also with the **current** Chrome and FF browser because I got the information that "older" versions are not affected.
<br>

![2019-10-02_WebChat Fullscreen_01](https://user-images.githubusercontent.com/30147533/66050211-0f084500-e52d-11e9-9e17-26ca082a1a42.png)

**Comment by ChaosKid42** [comment]
I'm quite sure that the chat boxes staying empty and the error message after logout are two different issues. The latter is already solved by https://github.com/conversejs/converse.js/commit/463caf36a156ecb53411557e1360df61c6c05f45

**Comment by MotoGP-Fan** [comment]
**@ChaosKid42:** Yes, you are right. After updating to Converse 5.0.4 the error message "Connection failure ..." no longer appears. But chat boxes still stay empty after Login (without reloading the page).

**Comment by ChaosKid42** [comment]
@MotoGP-Fan: Made a pull request for my solution to the problem: https://github.com/conversejs/converse.js/pull/1750. However, I believe there has to be a better solution, which unfortunately I'm not capable of implementing :-)

**Comment by jcbrand** [comment]
> Trusted device off and log in

I recently updated the code to wipe messages when you log out in untrusted ode, but I see that was after this issue was created:
https://github.com/conversejs/converse.js/commit/fdb24122c048cb130c5a92134dcfd9b318866046

**Comment by ChaosKid42** [comment]
@jcbrand If I leave the checkbox "trusted" unchecked then the chatboxes will stay empty after relogin. In case i set the checkbox to "trusted" then the chatboxes won't open at all :-(
