### ISSUE TITLE
Conversejs error after migration from 3.3.4 to 5.0.3

### ISSUE THREAD

**Issue by rheman** [conversejs/converse.js#1743]
Hi I used to use conversejs 3.3.4 on my website with AMD; requirejs and it worked perfectly.
Today we have decided to migrate from 3.3.4 to  5.0.3 and we get an error.

xmpp sever: ejabberd 19
Linux server: ubunti 19.09
converjs 5.0.3

When Initializing Converse I get the following error :

TypeError: converse is undefined

Could someone help me ?

Regards;

**Comment by licaon-kter** [comment]
Index contents? Bosh or WS?

**Comment by jcbrand** [comment]
Also, how are you loading Converse?

**Comment by rheman** [comment]
Index contents is Bosh.
```
<link rel="stylesheet" type="text/css" media="screen" href="https://cdn.conversejs.org/5.0.3/dist/converse.min.css">
<script src="https://cdn.conversejs.org/5.0.3/dist/converse.min.js" charset="utf-8"></script>
```
I cannot use the above statements because they are not supported in the opensource social media I am using. So I am using a build in function provided by the opensource social media I am using to load Converse and it works with 3.3.4 .

Regards,

**Comment by jcbrand** [comment]
@rheman You already created a ticket for this in #1737 and I closed it.

This issue tracker is for bug reports and feature requests, this issue is neither.

I can't help you integrate Converse into some other kind of system I've never heard of before and especially not if I have no idea how that system loads its scripts.

I'm sorry, in an ideal world I could just tell you what's wrong and you'd be on your way but it doesn't always work like that. You'll have to figure out what's going on by yourself, or you have to come back with real information as to what the underlying technical problem is and how we can help by making a change to Converse. Otherwise it's up to you to figure this out. It's after all your job.
