### ISSUE TITLE
_converse.room_list_view contains normal contacts

### ISSUE THREAD

**Issue by worlword** [conversejs/converse.js#1758]
Hello,

as far as I understand the `_converse.rooms_list_view` should contain only MUCs. But when I try to use it, I also get contacts inside the list. In the screenshot you can see that the list contains _controlbox_ and _tetser_nils@localhost_.
My Roster only contains _tester_nils_ and nothing else. No MUC etc.

If this behaviour is intended please rename the variable. Then I have to find my own way to get the MUCs.
<img width="729" alt="room_list_view_contains_normal_chat" src="https://user-images.githubusercontent.com/38032700/66978507-8223c680-f0aa-11e9-8c15-ecf968e3713c.PNG">

**Comment by jcbrand** [comment]
This was refactored recently.

`_converse.rooms_list_view` is a view that shows a list of open MUCs. Its associated model is `_converse.chatboxes` which contains ALL chat boxes (including the controlbox), not just MUCs.

The `rooms_list_view` is only one of several possible views that might apply to `_converse.chatboxes` and the views aren't obligated to show all chatboxes in `_converse.chatboxes`.

Renaming it doesn't make sense, because it does what it the name says. The fact that it's associated model contains more chatboxes than are shown isn't just an implementation detail that exists to avoid duplication of data. In other words, it's better to have one data source and multiple views on that, than multiple partially overlapping data sources so that each view has it's own data source.

To get a list of MUCs, use the API: `_converse.api.rooms.get()`
