### ISSUE TITLE
prebind authentication error

### ISSUE THREAD

**Issue by PIWAL** [conversejs/converse.js#1782]
Hi everyone,
I am using the latest release of conversejs.
I changed the webpack config of Converse.js. I set libraryTarget to `umd` because I because the web app where I want to use conversejs is `amd` compatible.
So I rebuilt the dist files with `make dist`.

Conversejs works good but I got some errors when using `prebind authentication` with `prebind_url`.

Here is the error I am getting.
`
TypeError: e.stream_features is undefined converse-disco.js:416:24`

I need help.

Regards,

**Comment by jcbrand** [comment]
Sorry but if the problem only occurs when you set the libraryTarget to `umd`, then I'm going to mark this issue as `wontfix`.

We don't officially support UMD and I'm not going to make a UMD build and configure it with prebind (for which I don't have a backend handy) just so that I can debug this issue.
