### ISSUE TITLE
credential_url

### ISSUE THREAD

**Issue by ColinRyan** [conversejs/converse.js#1838]
**Describe the bug**
So this is in the documentation and may not qualify as a bug but the description of the credentials url doesn't really explain where I get it, what it's format is or how I'm suppose to know. Is it something specific to each xmpp server? Any details would be helpful :)

**To Reproduce**
1. check the docs on configuration for credentials URL

**Expected behavior**
I would better understand what I'm looking at.

**Comment by bhattaxay** [comment]
@ColinRyan here you have to return json data from you credential_url in below format

`{jid: "test@localhost", password: "123@localhost"}`

**Comment by jcbrand** [comment]
The documentation does explain the JSON format that needs to be returned by the server:
https://conversejs.org/docs/html/configuration.html#credentials-url

It's up to you to set up and probably create the backend that provides the credentials JSON and it's up to you to decide and define where those credentials come from and this can vary a lot between deployments, which is why the documentation cannot be too explicit about that.

**Comment by ColinRyan** [comment]
@jcbrand Thanks for getting back to me. I haven't had to utilize xmpp before now so at a glance I was left confused  about how I might use this config option with something like OpenFire or if it was only for custom servers. I was trying to figure out how to reconnect to a session but I ended up learning enough about pre_bind to make that work for me :D.
