### ISSUE TITLE
OpenStreetMap URL parameters discarded

### ISSUE THREAD

**Issue by Zash** [conversejs/converse.js#1850]
**Describe the bug**
Converse.js turns OSM URLs into `geo:` URIs. This is nice, however if there is more information than just a geo-position in the URL then this is lost.

**To Reproduce**
1. Go to <https://www.openstreetmap.org/>
2. Create a route / directions
3. Copy the resulting URL ([example](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=51.507%2C-0.128%3B52.517%2C13.389#map=7/51.727/6.636))
4. Paste in a chat in Converse.js

**Expected behavior**
The full URL including `/directions?route=...` should be preserved.

**Environment:**
 - Desktop
 - Firefox 72.0.2
 - Converse.js 6.0.0

**Comment by jcbrand** [comment]
> Converse.js turns OSM URLs into geo: URIs. This is nice

I've been thinking about this "feature" since looking at @ShehanAT's PR #2914, and I've come to the conclusion that this is actually an anti-feature. I'm not sure where the desire for this feature came from, I think someone asked for it but I didn't find the ticket yet.

Converse shouldn't just automatically change people's URLs, even if this is somehow nicer for a recipient using Conversations.
If Converse is to change an OSM URL into a `geo:` URI, then it needs to be with the explicit consent or command of the user. 

Converse could instead use a XEP-0372 reference to include a `geo:` URI with an ORM URL, but since no client would support that AFAIK I'm not sure that it's worth the effort.

Another option would be to have a dedicated button on the chat toolbar for sharing your location.

**Comment by deleolajide** [comment]
> Another option would be to have a dedicated button on the chat toolbar for sharing your location.

That is what the location plugin does 👍 
https://github.com/conversejs/community-plugins/tree/master/packages/location

**Comment by jcbrand** [comment]
Cool, good to know @deleolajide 

I've removed the auto-conversion of OSM URLs to `geo:` URIs, so I think this issue can be closed.
