### ISSUE TITLE
Use the system libsass when available

### ISSUE THREAD

**Issue by linkmauve** [conversejs/converse.js#1936]
**Is your feature request related to a problem? Please describe.**
#1935 causes an issue when building libsass, but there should be no reason to build it since this library is already available on my system.

**Describe the solution you'd like**
First check with `pkg-config libsass` whether it is installed, and use it if it is.

**Describe alternatives you've considered**
This sounds like the best solution.

**Additional context**
N/A

**Comment by jcbrand** [comment]
The point of using `node-sass` is so that we don't have to depend on `libsass` on the system and so that we can have a reproducible environment for people.

I recently updated to a newer version of `node-sass` and then had to add `npm rebuild node-sass` to the Makefile to fix an issue with NPM switching libsass versions during build.

Can you please check whether your problem goes away after that change?
