### ISSUE TITLE
Is it possible to use only the part of xmpp to connect and send messages without using the user interface

### ISSUE THREAD

**Issue by coder-free** [conversejs/converse.js#1994]
my environment has no dom and bom environment, maybe like nodejs. I want use converse connect to my xmpp server and send message, maybe join room and send message, I do not need any UI, Is it possible?

**Comment by jcbrand** [comment]
You can try to use the headless build of Converse.

https://www.npmjs.com/package/@converse/headless

It's not supposed to have a strict dependency on the DOM, although I can't 100% guarantee it, since I haven't ever used it without a DOM.

If you're going to use it, be aware of this bug:
https://github.com/conversejs/converse.js/issues/1961

Alternatively you can try to use a library like Strophe.js (https://strophe.im) or Stanza (https://github.com/legastero/stanza). They might be better suited to your needs, but then you'll have to implement a lot of functionality that @converse/headless provides to you, like support for groupchats, stream resumption (XEP-0198), automatic reconnection, service discovery (XEP-0030) and more.

Can you give some more information about your environment?

xmpp.js is another library option: https://github.com/xmppjs/xmpp.js

**Comment by zfavourite99** [comment]
Thanks for your reply. I have seen strophe before. For me, the workload of re-implementing XEP-0198 or XEP-0030 is a bit heavy, and the stability of my own implementation may be poor. Regarding xmpp.js, I did not see any documentation about MUC, I think it may not implement XEP-0045.

So my best choice might be converse.

Abort my environment, you can see this [page](https://developers.weixin.qq.com/minigame/dev/guide/best-practice/adapter.html) maybe need translate.
The environment is javascriptCore on ios and v8 on android. both have no dom environment.

**Comment by jcbrand** [comment]
I'll try to make a 6.0.2 release of Converse.js and @converse/headless this week.  Then #1961 will be fixed.
