### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by vampik** [conversejs/converse.js#2067]
**Describe the bug**
Unable to login.

**To Reproduce**
1. Go to the webpage hosting converse.js
2. Enter login and password
3. Click on 'Log in'

**Expected behavior**
It is expected to be able to log in

**Environment (please complete the following information):**
 - Desktop
 - Chrome and Firefox
 - 6.0.1dev (latest master)

**Additional context**

I get the following error after entering the right login and password:

"Authentication failure
Your XMPP address and/or password is incorrect. Please try again."

Version 6.0.1 worked fine. Current 6.0.1dev (master) doesn't work.

I've checked the logs of my server (ejabberd 20.04):

converse.js 6.0.1:
<0.22883.0>@ejabberd_c2s:process_auth_result/3:270 (websocket|<0.22882.0>) Accepted c2s SCRAM-SHA-1 authentication for xxxx@xxxxxx.xx by sql backend from ::ffff:xxx.xxx.xxx.xxx

converse.js master:
<0.589.0>@ejabberd_c2s:process_auth_result/3:278 (websocket|<0.588.0>) Failed c2s X-OAUTH2 authentication for xxxx@xxxxxx.xx from ::ffff:xxx.xxx.xxx.xxx: Invalid token

**Comment by licaon-kter** [comment]
@vampik disable that https://docs.ejabberd.im/developer/ejabberd-api/oauth/#authentication-method

**Comment by vampik** [comment]
> @vampik disable that https://docs.ejabberd.im/developer/ejabberd-api/oauth/#authentication-method

Looks like it works after disabling this server-side.

But nevertheless it seems to be a conversejs issue.

Version 6.0.1 works just fine as well as another XMPP clients.

**Comment by jcbrand** [comment]
I think it might be related to this, which I still need to fix:

https://github.com/strophe/strophejs/issues/350

**Comment by 9d1** [comment]
i have this issue on 6.0.1

**Comment by 9d1** [comment]
```
2020-06-08 12:49:03.442 [warning] <0.212.0>@ejabberd_auth_mnesia:need_transform:221 Some passwords were stored in the database as SCRAM, but 'auth_password_format' is not configured as 'scram': some authentication mechanisms such as DIGEST-MD5 would *fail*
2020-06-08 12:49:22.239 [warning] <0.541.0>@ejabberd_c2s:process_auth_result:278 (websocket|<0.540.0>) Failed c2s SCRAM-SHA-1 authentication for <redacted> from ::ffff:10.7.0.2: Invalid username or password
```

**Comment by jcbrand** [comment]
@9d1 Looks more like an ejabbberd configuration error. You don't have `auth_password_format` configured as `scram` but some passwords are saved in the database as SCRAM passwords.

**Comment by 9d1** [comment]
@jcbrand that's because i switched from scram to plain, because of this error

**Comment by averyberry** [comment]
Hi There, first time posting here :)  I wanted to add some more info, as I am having an issue similar to this and I think it is related.  

My app uses auto login and credentials url that passes JID and a token for login and has been working fine across page loads and multiple times in a session. I had been building off of the tagged 6.0.1 release, and yesterday I started building converse head rev since y'all seem close to v7 and I wanted all the goodies (looks great btw!). 

Now, first page load with a clear cache, auto login works as expected. If I reload, autologin fails to initialize and I get the password entry form in converse. If i clear cache and reload the page it works again.  And this is weird, if i open the same page in a new tab (firefox, or chrome) auto login works every time. IOW, if i reload the page auto login fails, if I reload the page in a new tab auto login succeeds as many tabs as I open and load.  This is new behavior as of head revision this was not happening as of 6.0.1.

**Comment by jcbrand** [comment]
@averyberry: thanks for the info, however it doesn't look to me like your problem is the same as the one described in this bug report.

I've now released Strophe.js 1.3.6 and updated Converse.js to use it, so I think this issue is now fixed.

If you still have your problem @averyberry, then please create a new bug report with the same information.
