### ISSUE TITLE
Can't scroll up to get older messages if already up

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#2134]
...I need to scroll down a bit and then scroll up again

HEAD (cca5c17ccb024c605b5bb397cf6c7423fce08de3), Firefox 78, Vivaldi Snapshot

**Comment by Zash** [comment]
Assuming this is the same thing I'm thinking of:

Steps to reproduce:
0. Join a chat with MAM available.
1. Scroll up all the way to the top.
2. It should start fetching messages from archive.
3. Wait for it to load those.
4. Try scrolling up more.

Expect: Possible to scroll further and have it load more messages.

Actual: What the first comment says, can't scroll up because it's still scrolled all the way to the top.

**Comment by licaon-kter** [comment]
Same thing on mobile, swipe triggers the "end of scroll" animation, but none the less scroll up down a bit then pull again...more messages get downloaded.

**Comment by licaon-kter** [comment]
Looks fixed to me, @Zash  ?

**Comment by Zash** [comment]
Can't scroll at all anymore. I'm told my Firefox is too old.

**Comment by jcbrand** [comment]
Yes, join the 21st century old man.

**Comment by Zash** [comment]
No! Debian Stable gives me Firefox ESR, so that's what I'll use.
