### ISSUE TITLE
Ability to trigger ad-hoc command on a certain JID right after login

### ISSUE THREAD

**Issue by singpolyma** [conversejs/converse.js#2163]
I would love to be able to have the list of commands for some JID come up right after the session starts.  I don't need this to be super pretty (ie: doesn't have to be a config option or anything) and happy to write a custom plugin for it, but right now it seems the whole UI assumes it is being opened by submitting a form with the JID is a field, whereas I would like to provide the JID as an argument to an API that will pop up the modal with the right list.

I actually then want to disable the rest of the UI, but I can just fake that by hiding it with CSS or similar.  The main thing is to get the settings modal (or a new modal I can create with the right component in it?) popped up to the ad hoc panel, and already submitted with the correct JID.

In case it's not obvious, I'm trying to create a web-based "settings panel" option for my ad-hoc configured XMPP component.

**Comment by jcbrand** [comment]
To do what you want to do, you'd have to make lots of customizations.

If you only want to display a settings panel to the user and nothing else, then you can disable all kinds of plugins (or better yet, remove them entirely from your build), because you won't need them.

Some that come to mind:

* converse-muc
* converse-muc-views
* converse-headlines
* converse-chat
* converse-chatviews
* converse-register
* converse-rosterviews

And probably more.

Then you can create a new modal that's similar to the Ad-Hoc commands modal, but that automatically fetches the commands for a particular JID.

Seems totally doable, but would require some understanding of how Converse.js fits together and how to customize it via plugins.

This ticket isn't related to a bug or feature request (if it's a feature request, then I'm declining it, sorry), so I'm closing it.

**Comment by singpolyma** [comment]
>Then you can create a new modal that's similar to the Ad-Hoc commands 
>modal, but that automatically fetches the commands for a particular JID.

Is there any reason I couldn't just pop the existing modal, but with a jid 
already filled in?

I *think* from reading the code it would just require an entry point taking 
a jid instead of a form submit event.

**Comment by jcbrand** [comment]
> Is there any reason I couldn't just pop the existing modal, but with a jid
already filled in?

If there's a clean way to do that, then go for it.
