### ISSUE TITLE
after reconnect Message Carbons get changed from enable to disable.

### ISSUE THREAD

**Issue by PrakashPaul** [conversejs/converse.js#2293]
**Describe the bug**
while user login, user Message Carbons property set to enabled 
_converse.connection.send(carbons_iq);
but when reconnect happend  enableCarbons() method called but _converse.connection.send(carbons_iq); not execute.

To Reproduce

User login for chat app.
after login check user session details in openfire server [Message Carbons : Enabled]
disconnect internet for 2-3 min then connect again
after 20 sec you will notice reconnect successfully done.
check user session details in openfire server [Message Carbons : Disabled].

Environment (please complete the following information):
LAPTOP(window 10)
Chrome Version 72.0.3626.121
Converse Version v6.0.0

**Comment by jcbrand** [comment]
Carbons are enabled in the [enableCarbons](https://github.com/conversejs/converse.js/blob/042aa3a73ea894dd024a7f14cb7727ecabb80ea1/src/headless/converse-carbons.js#L16) function, which gets called as event handler for the `afterResourceBinding` event.

Looks like that event also triggers after reconnecting, so I'm not sure what the issue is. Could be that the session doesn't get cleared properly, so that `_converse.session?.get('carbons_enabled')` returns `true`.
