### ISSUE TITLE
Conversejs for Internet Explorer

### ISSUE THREAD

**Issue by juancar0505** [conversejs/converse.js#2421]
Is there any version or some way to integrate converse in Internet Explorer. 
With the last version i get this error

![image](https://user-images.githubusercontent.com/70941752/109785158-25c43700-7c0c-11eb-9470-97b207e1c5eb.png)

**Comment by jcbrand** [comment]
Converse uses newer browser APIs and JavaScript language features that are not available in IE.

You could try updating Babel in the webpack configuration to target IE, but that might not be enough because I think you'll also need some polyfills for built-in functions that aren't available in IE.

Perhaps possible, but not something I'm going to work on.

**Comment by juancar0505** [comment]
@jcbrand is there any version of converse wich can be build on IE11?

**Comment by jcbrand** [comment]
Version 3.3.2 still had some fixes for IE11, so that should still work.
https://github.com/conversejs/converse.js/releases/tag/3.3.2

Don't use 3.3.2 however, use 3.3.4 instead, so that you get the important security fixes.
