### ISSUE TITLE
Wrong assignment in the OMEMO code ?

### ISSUE THREAD

**Issue by edhelas** [conversejs/converse.js#2500]
https://github.com/conversejs/converse.js/blob/06f03fc8842296288b9a045c71623c442421e232/src/plugins/omemo/store.js#L240

I'm not sure if it's an issue or if I didn't understood something there.

**Comment by Echolon** [comment]
@jcbrand is this critical?

**Comment by jcbrand** [comment]
@Echolon Sorry, I was away traveling the last two weeks.

This is indeed a bug, but as far as I can tell this is not critical since that value is only stored locally and used by libsignal's session builder for verification.

I'll make a new version 7 release in any case.

**Comment by Echolon** [comment]
Alright - no need to be sorry. Just pinging that you see this!

7 jun. 2021 1:29:16 PM JC Brand ***@***.***>:

**Comment by jcbrand** [comment]
Just for more context.

I've looked at the underlying signal code, and here's my understanding of what happened.

The signed prekey is a public/private keypair where the signature is the public key being signed by the private key.

That's being generated via libsignal here: https://github.com/conversejs/converse.js/blob/90dff612c7364585032f571b755aca085b28040c/src/plugins/omemo/store.js#L235

The signed prekey values are then stored in *two* different places. The [OMEMOStore](https://github.com/conversejs/converse.js/blob/90dff612c7364585032f571b755aca085b28040c/src/plugins/omemo/store.js) and the [device](https://github.com/conversejs/converse.js/blob/90dff612c7364585032f571b755aca085b28040c/src/plugins/omemo/device.js).

The `OMEMOStore` is what's required and used by libsignal and is what's used to broadcast the prekeys to other users.
See here:
https://github.com/conversejs/converse.js/blob/90dff612c7364585032f571b755aca085b28040c/src/plugins/omemo/store.js#L237

The `device` object is mainly used to keep track of the prekeys of *other* users (i.e. contacts) since we don't have an `OMEMOStore` instance for all of them.

Out of a (perhaps misguided) sense of completeness, I also stored the current user's prekey data in their `device` object.
However, this (until now wrongly stored) signed prekey data was not being used anywhere. It was not broadcast to other users and was not used to verify or sign anything.
