### ISSUE TITLE
ConverseJS can't send omemo messages to our mobile users.  

### ISSUE THREAD

**Issue by nedmhtechnologies** [conversejs/converse.js#2710]
**Describe the bug**
ConverseJS can't send omemo messages to our mobile users.  some users ok, but some will have errors and cannot be sent.
mobile to mobile is fine. we suspect converseJS has an omemo issue.

**To Reproduce**
my issue with ConverseJS is that when we enabled omemo.  We send messages to our clinitok mobile app. sometimes it can send, sometimes it cannot send.  but if we disabled omemo, it works fine.

**Expected behavior**
It should send the message if omemo is enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/85239562/139670694-0a188f79-b97c-48dd-8766-e54b05f6a7ab.png)
![image](https://user-images.githubusercontent.com/85239562/139670714-a4e39fca-88f4-4dd0-9922-ce091e6ffd28.png)

**Environment 
 - Browser Chrome
 - Converse.js version 8.0.1

**Comment by jcbrand** [comment]
The most likely cause here is that the messages weren't encrypted for those mobile devices, which is why they don't show up in those devices.

New devices are publicised via PEP, and there are a few things that might be going wrong.

For example:
* Converse might not be getting newly published devices on the PEP node
* Devices might disappear from the PEP node (e.g. due to client bugs)

There isn't enough information in your bug report to know what is going on and/or how to fix it.

You can inspect Converse's state in the browser developer console to see how many devices it has per user.

For example:
```
_converse.devicelists.get('user@chat.example.org').devices.map(d => d.id)
(10) ['5664', '6855', '1607898749', '3581', '11799', '6809', '16076', '1788', '3233', '598099768']
```
