### ISSUE TITLE
Chrome: lot of Disconnection / Reconnection logged into a chatbox

### ISSUE THREAD

**Issue by SilverYoCha** [conversejs/converse.js#2770]
**Describe the bug**
When a user is using a Chrome or Chrome like browser the other users see lot of disconnection / reconnection from this user info chat or group chat room.
Have someone got same observation?
Still, their internet connection works perfectly.

**To Reproduce**
One user on Firefox and an other on a Chrome or Chrome like chatting between each other.
After a while, the user on Firefox will see regular disconnections / reconnections from Chrome user.

**Expected behavior**
Avoiding to get the disconnections / reconnections.

**Screenshots**
For example: 
![image](https://user-images.githubusercontent.com/1503467/148738051-7a8ca1de-7234-41aa-93a9-4b2838f1f408.png)

**Environment**
 - Desktop
 - Browser Chrome (recent version)
 - Converse.js version 9.0.0

**Comment by licaon-kter** [comment]
Console log, debug level, says what?

**Comment by SilverYoCha** [comment]
I tried to capture some logs after detecting the thing.
Not sure to get enough.

The context:
* an opened chat (one to one) between userA and userB (userB on Chrome and userA on Firefox)
* an opened group chat where userA and userB are also participants

[console-export-2022-1-10_12-7-31.txt](https://github.com/conversejs/converse.js/files/7838444/console-export-2022-1-10_12-7-31.txt)

**Comment by jcbrand** [comment]
I don't see anything in those logs, are they from the Firefox user?

I think it would be better to set your server's logs to debug level and see what gets logged there.

**Comment by licaon-kter** [comment]
@SilverYoCha why is your picture blue? Whah theme is that? How did you install Converse?

**Comment by SilverYoCha** [comment]
@jcbrand yes logs comes from Firefox user.
OK, I will try to investigate the logs on the ejabberd server.

@licaon-kter default theme is used. There is just some CSS changes defined into an external CSS file.
ConverseJS is used in overlayed mode.
<details>
  <summary>Initialization options</summary>

```
 converse.initialize({
          'view_mode' : 'overlayed',
          'i18n' : 'a language',
          'assets_path' : '/myserver/chat/converse/',
          'sounds_path' : '/myserver/chat/converse/',
          'play_sounds' : false,
          'bosh_service_url' : 'bosh url',
          'allow_logout' : false,
          'auto_login' : true,
          'auto_reconnect' : true,
          'jid' : 'a jid',
          'default_domain' : 'a domain',
          'domain_placeholder' : 'a domain',
          'password' : 'a password',
          'autocomplete_add_contact' : false,
          'notification_icon' : 'aLogo.png',
          'muc_domain' : 'conference.a.domain',
          'locked_muc_domain' : 'hidden',
          'muc_disable_slash_commands' : true,
          'locked_muc_nickname' : true,
          'nickname' : 'a nickname',
          'auto_register_muc_nickname' : true,
          'notify_all_room_messages' : true,
          'auto_join_on_invite' : false,
          'roster_groups' : false,
          'allow_adhoc_commands' : false,
          'allow_contact_removal' : false,
          'allow_contact_requests' : false,
          'allow_registration' : false,
          'show_controlbox_by_default' : false,
          'discover_connection_methods' : false
        });
```

</details>

**Comment by jcbrand** [comment]
@SilverYoCha Concerning Converse logs, the logs from the Chrome user will be more useful than from the Firefox user.

**Comment by SilverYoCha** [comment]
@jcbrand I got logs of my interlocutor which is using a chrome like browser.
Hope it can be helpful.

userA uses Firefox and userB the chrome like browser
<details>
  <summary>Chrome like browser details</summary>

```
Vicaldi 5.0.2497.32 (Stable channel) stable (64 bits)
Révision    4891cb2a30270ebb895cf22eb99642090bde0046
Système d’exploitation    Linux
JavaScript    V8 9.6.180.21
Agent utilisateur    Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.113 Safari/537.36
Ligne de commande    /usr/bin/vivaldi-stable --new-window --enable-crashpad --flag-switches-begin --flag-switches-end --origin-trial-disabled-features=CaptureHandle --save-page-as-mhtml
Chemin d’accès à l’exécutable    /opt/vivaldi/vivaldi
Chemin d’accès au profil    /home/dle/.config/vivaldi/Default
```

</details>

[server.com-1641898021606.log](https://github.com/conversejs/converse.js/files/7846911/server.com-1641898021606.log)

**Comment by JohnXLivingston** [comment]
I use ConverseJS in a Peertube plugin (Peertube is a FOSS streaming platform). I have a user that seems to have the same issue: https://github.com/JohnXLivingston/peertube-plugin-livechat/issues/88

The browser logs are in the screenshots.

ConverseJS can't reconnect, but this is maybe due to the way I use Converse (i will investigate next week).

**Comment by jcbrand** [comment]
@SilverYoCha: I see that the person is using BOSH to connect instead of websocket.

At some point, the XMPP server returns:
```
log.js:70  2022-01-11T10:44:20.660Z DEBUG: <body xmlns="http://jabber.org/protocol/httpbind" type="terminate" condition="item-not-found"/>
```

This can happen for multiple reasons:
https://xmpp.org/extensions/xep-0124.html#table-2

I think you should check your XMPP server's logs for information as to why it terminates the BOSH session.
Might be that it has expired, or might have something to do with Chrome throttling requests (e.g. when the tab is in the background).

You can also just use websocket instead of BOSH. It's faster, simpler and better.

**Comment by JohnXLivingston** [comment]
@jcbrand , any idea of what explains the difference between Chrome and Firefox? Maybe Chrome closes some connections after a timeout when tab is in background?

**Comment by jcbrand** [comment]
@JohnXLivingston I think the issue is that Chrome throttles HTTP connections and that this causes the BOSH session to expire.

One possible solution could be to increase the BOSH `wait` period. You should apply the latest commit I made:
https://github.com/conversejs/converse.js/commit/007b4bce2ffe169c0c5cd276dfc4dba540a96001

And then you can change BOSH_WAIT to be some larger value. There's even a small change that my commit fixes the problem without changing the value.

Better yet would be to just use websocket.

**Comment by JohnXLivingston** [comment]
Thanks. I'll test that (not this week, I'm working on another project, but soon).

I can't use websocket in my project... (I have to use the Peertube server as a proxy, I can't add a websocket server).

**Comment by SilverYoCha** [comment]
Thank you for your recommendations @jcbrand.
I just set up websocket communications and it does indeed the job, and so, it fixes the problem.
I did not take time to try the commit https://github.com/conversejs/converse.js/commit/007b4bce2ffe169c0c5cd276dfc4dba540a96001 @JohnXLivingston , but I hope it will fix yours.
