### ISSUE TITLE
Retraction message does not have fallback body

### ISSUE THREAD

**Issue by mightymop** [conversejs/converse.js#2775]
**Describe the bug**
In XEP 424 it is recommended to add a fallback text (body) for clients which does not have message retraction feature.
Furthermore clients other than converse could rely on a body and maybe wont execute a message retraction if there is no fallback body... I've noticed too, that for example message archive plugin for openfire server also does not save messages without a body to MAM Archive, so a future mam request will provide the not retracted message to the client / to the user and could not get retracted after it.
The solution would be simply add the default text: "This person attempted to retract a previous message, but it's unsupported by your client."
I know XEP declares it as only recommended but it would be best practice to do so.

 - Converse.js version 9

**Comment by jcbrand** [comment]
After looking at XEP-0428 fallbacks, I'm not longer convinced of it's usefulness or relevance concerning XEP-424.

There is no other XEP except XEP-424 that references it, and I'm not sure that it really provides any benefit to explicitly add the fallback element (at least in the case of retractions). According to the XEP it's to help servers to not treat certain messages as "normal" messages, for example by not storing them in the MAM archive. But we DO want to store retractions in the archive.

In fact, I think XEP-428 adds more ambiguity and therefore makes it more difficult for a client to know what to do. The `fallback` element is optional, so what do we do if we get a special message (e.g. retraction, encrypted or reaction) that has a body and no `fallback`? Do we show the body or not? If we don't, then we don't need the `fallback` element. If we do show the body, then we run the risk of properly processing the message *and* unnecessarily showing a fallback message.

Also, the existence of a `fallback` element doesn't mean much, because the client still needs to figure out whether it supports the operations implied by the message, and if it needs to do that, it can infer from that context whether it needs to show the `body` or not.
 
 For example, if a client supports retractions, it can just always ignore the body, and doesn't need a `fallback` element in order to do so. Older clients that don't support reactions will automatically show the `body`, they also don't need a `fallback` to tell them to do that.
 
 I will update XEP-424 sometime to remove the requirement of adding a `fallback` element.
 
CC @dwd
