### ISSUE TITLE
OAuth icon does not appear on the login panel

### ISSUE THREAD

**Issue by cryoflamer** [conversejs/converse.js#2809]
**Describe the bug**
OAuth icon does not appear on the login panel

**To Reproduce**
1. Enable oauth.js plugin
2. On loading the login panel, a warning appears in the debug console:
  <pre>
> pluggable.js:144 Plugin "converse-oauth" tried to override "LoginPanel" but it's not found.
  </pre>

**Expected behavior**
The appearance of the OAuth icon or something similar

**Environment (please complete the following information):**
 - Any browsers (Chrome, Firefox etc)
 - Converse.js version 9.0.0

**Comment by robjloranger** [comment]
I'm just looking around the code and I think it's supposed to be overriding `LoginForm`. Although I might be way off. If no one else has time I can look tonight.

**Comment by jcbrand** [comment]
@robjloranger that would be great.

The oauth plugin is old and probably needs updating to be compatible with all the changes in Converse 9 (particularly the usage of web components instead of Backbone views).

It should also ideally be moved to the community plugins repo, since it's not used by default.

**Comment by robjloranger** [comment]
I'm still looking but have become busy with a home project, hoping to spend some time on this soon but will unassign in case someone wants to have a go in the meantime.
