### ISSUE TITLE
Add a way to add a MUC occupant to my roster

### ISSUE THREAD

**Issue by sloonz** [conversejs/converse.js#3061]
Right now, the only way to add a MUC occupant to my roster is to view its profile, copy its JID, close the profile, click on "Add Contact", paste the JID and add the contact. IMO, this is not very user-friendly. A better way would be (for example) to add a "Add to Contacts" button to the profile of the occupant.

I made an initial implementation here to open the discussion : https://github.com/sloonz/converse.js/commit/c2f5aa1d1adeb165d095dd18c76130b09c1a0135

**Comment by jcbrand** [comment]
Hi @sloonz, it's always nice to see people getting their hands dirty and adding the changes they want in the source code.

I think it's a useful feature, so please make a PR with your changes.

Some initial thoughts on your your implementation:

1. This will only work for MUCs where real JIDs are exposed, so a check needs to be added for that. In the context of the `OccupantModal` which you've already modified, you can do something like this:
```javascript
const muc = this.model.collection.chatbox;
if (muc.features.get('nonanonymous')) {
   // Real JIDs are exposed, so you can add occupants to your roster
}
```
2. Currently when you add a roster contact, you get presented a modal with the option to choose a `name` and `group`.  We'd want to keep that ability when adding from a MUC as well, so when `Add to contacts` is clicked, the `Add a contact` modal should be shown (with the `XMPP Address` and `Name` inputs pre-filled) so that the user can still set their own values for `Name` and `Group`.

Opening a new modal is fairly simple, when the `Add to contacts` button is clicked, you can open the next modal like this:
```javascript
api.modal.show('converse-add-contact-modal', {'model': new Model()}, ev);
```

**Comment by sloonz** [comment]
Done. I also hide the button for the user (so you can't add yourself). The button is also hidden for moderators / owners in anonymous rooms even tho they can see the JID of the occupant, not sure it’s the correct choice.

**Comment by deleolajide** [comment]
@sloonz Could you please consider add another button to start a chat with contact. Sometime, I just want to chat and don't need to add the contact to my roster.

I currently do that in Pade direct from the participants list and the additional button in the dialog will be consistent with that. 

![image](https://user-images.githubusercontent.com/110731/199216964-117ac6af-4c47-4f70-8116-818c043aef00.png)

**Comment by jcbrand** [comment]
Closing this ticket now since it's been implemented. @deleolajide You're asking for a new feature, so it should please go into a new ticket.

**Comment by deleolajide** [comment]
>You're asking for a new feature, so it should please go into a new ticket.

👍 I am adding this screenshot as a reminder

![image](https://user-images.githubusercontent.com/110731/199691233-6703f266-ad13-4d14-a1ac-619fbecf3ead.png)
