### ISSUE TITLE
Usage of 'nickname' and 'fullname' in converse.initialize()

### ISSUE THREAD

**Issue by brneor** [conversejs/converse.js#3165]
According to the docs [here](https://conversejs.org/docs/html/configuration.html#nickname) and [here](https://conversejs.org/docs/html/configuration.html#fullname), if _nickname_ and _fullname_ options are set, these values are used instead the ones in vcard.

As any of the users in my server have vcards, I tried to set this options but I can't see it being reflected in the interface:

![image](https://github.com/conversejs/converse.js/assets/5962898/c848b424-e881-4d70-8153-0bcd8cfca08d)

Instead what I'm seeing is the random _jid_ that my application generates which is used by a prebind service.

Am I missing something here? Is this the expected behavior?

**Comment by jcbrand** [comment]
I've removed the documentation for the `fullname` option. It's ancient and looks like whatever functionality it had has been removed (refactored out) over the years.

Besides that, I've made a change so that if a `nickname` is specified, it's shown in the profile (like in your screenshot).

Let me know if there's something else that you expected with regards to the nickname setting.
