### ISSUE TITLE
conversejs.org says "Your IP address is blocklisted" with no suggested resolution

### ISSUE THREAD

**Issue by HansLachman** [conversejs/converse.js#3466]
Please note:  before closing this issue, or berating me for being off-topic, please note that I'm doing my best to follow the instructions given at conversejs.org.  The home page says "For technical support, you can ask on Stack Overflow", so I did that and was berated for being off-topic.  The home page also says "Please file bugs and feature requests on Github" and what I'm reporting appears to be a bug (as the error message I got appears to be erroneous).  In addition, the StackOverflow person who rejected my inquiry suggested I post my issue on your Github page.  So here it is.  Below is a copy of what I posted there ( https://stackoverflow.com/staging-ground/78813980 ).  If this is the incorrect way to pursue this issue, please tell me what the correct way is.  Thanks for your attention to my inquiry.

-- (full description of issue, originally posted on stackoverflow) --

Please excuse me if this is the wrong place for my question, but the conversejs.org home page directed me here "For technical support".

I have never used XMPP and want to try it. Starting at xmpp.org/getting-started I found conversejs.org, clicked "fullpage" then clicked "Create an account", selected xmpp.earth as provider, then entered my preferred username/password and submitted the form. I got the error message "Your IP address is blocklisted" with no further advice (the rest of the page was just the Account Registration form again).

I did a web search to figure out what it means, and found a blocklist/blacklist checker at whatismyipaddress.com/blacklist-check, which told me that my IP is "Not Listed (Good!)" everywhere it checked. I got the same result at other similar sites.

Then I did a search (on this site, and on Google) to see if this is a known problem with conversejs.org, and didn't find anyone else discussing this issue.

Is there a way to find out what is causing this error, and how to resolve that cause? Thanks.

**Comment by jcbrand** [comment]
Hi, I'm sorry that it's been such a pain.

If you're using xmpp.earth as provider, and you get that message, then the message is coming from that server, and not from Converse itself.

If you were to use conversejs.org as provider, you'd get the same message, because I've disallowed in-band registration from all IP addresses except one. I got tired of fighting spammers and scammers, so I've closed registrations on my server.

My guess is that the xmpp.earth admin has done something similar.

You can try reaching out to them, or you can register an account somewhere else.

In-band registration such as what Converse provides is often blocked by server providers because it gets abused by spammers. So if I was you I'd look for a provider where you can sign up on their own website, and then when you have the login details, you can still use Converse to log in.

For example here is a provider where you can sign up on their own website: https://404.city/

I have no affiliation with them, don't know the admin, and have never used the service, it was just the first result that came up with a quick search.

**Comment by HansLachman** [comment]
Thanks for your suggestions, I will try alternate avenues to proceed, as you suggest.

In the meantime, may I provide feedback and suggestions about conversejs.org that may be of practical value to your users?

(1) I suggest you change "For technical support, you can ask on Stack Overflow" to "For programming-related support, you can ask on Stack Overflow".  This will help to avoid situations like mine, getting sent to the wrong site for support, inconveniencing not only myself but the people at StackOverflow.

(2) From your explanation, it sounds like my IP is not listed on a blocklist, it's actually just not listed on a whitelist (which is limited to the provider's own IP).  So conversejs.org should display some error message other than one that's arguably a false statement (i.e., you shouldn't tell the user that their IP is on a blocklist when it's not).  As it stands, this situation caused me to go on a wild goose chase to check with blocklist providers all over the Internet, and I feel that's it's wrong to cause the user to do that.

(2) If an error is generated by the provider (like xmpp.earth), then conversejs.org should refer the user to the provider for support.  Otherwise, I have no way to know that I should try to contact them rather than post here on your Github page, as from my point of view, conversejs.org is the entity that gave me the error message.
