### ISSUE TITLE
When joining a room, use the vCard name first, or if unset the localpart of the JID, or if anonymous remember when it was first asked

### ISSUE THREAD

**Issue by linkmauve** [conversejs/converse.js#968]
When a user joins multiple rooms, asking them every time what their nick is is cumbersome.  It would be much better to default to a sensible value, while letting the user configure that.

**Comment by jcbrand** [comment]
Ok, so what happens now...

1. First Converse checks whether the user has a nickname registered with the room.
2. Then it checks if the user has a nickname set in their VCard.
3. Then, if `muc_nickname_from_jid` is true, it will use the localpart of the JID
4. Otherwise it renders the nickname form.

I don't think it's worth the extra hassle to remember the nickname if the user doesn't have it set in their VCard. If you don't want to be asked every time, then set your VCard (which can now be done in Converse).
